// 扩展内部消息类型常量（chrome.runtime.sendMessage）

export const MessageType = {
  // background <-> popup/app
  PING_BACKGROUND: 'PING_BACKGROUND',
  OPEN_APP_PAGE: 'OPEN_APP_PAGE',

  // background <-> content script
  PING: 'PING',
  CONTENT_GET_PAGE_STATUS: 'CONTENT_GET_PAGE_STATUS',
  CONTENT_INJECT_TEXT: 'CONTENT_INJECT_TEXT',
  AGTALK_INCOMING: 'AGTALK_INCOMING',

  // shared API 消息：popup/app -> background
  API_HEALTH_CHECK: 'API_HEALTH_CHECK',
  API_GET_STATUS: 'API_GET_STATUS',
  API_GET_CONFIG: 'API_GET_CONFIG',
  API_SAVE_CONFIG: 'API_SAVE_CONFIG',
  API_GET_CONVERSATIONS: 'API_GET_CONVERSATIONS',
  API_GET_CONVERSATION_MESSAGES: 'API_GET_CONVERSATION_MESSAGES',
  API_SEND_REPLY: 'API_SEND_REPLY',
  API_GET_LOGS: 'API_GET_LOGS',

  // 旧业务消息（保留常量，Phase 2 不迁移实现）
  CHAT_TURN: 'CHAT_TURN',
  AGTALK_SEND: 'AGTALK_SEND',
  GET_CONFIG: 'GET_CONFIG',
  SAVE_CONFIG: 'SAVE_CONFIG',
  REGISTER_AGENT: 'REGISTER_AGENT',
  RECONNECT: 'RECONNECT',
  GET_RECENT_MESSAGES: 'GET_RECENT_MESSAGES',
  SEARCH_MESSAGES: 'SEARCH_MESSAGES',
  AGTALK_INBOX: 'AGTALK_INBOX',
  AGTALK_INBOX_STATS: 'AGTALK_INBOX_STATS',
  AGTALK_MARK_DONE: 'AGTALK_MARK_DONE',
  AGTALK_MARK_READ: 'AGTALK_MARK_READ',
  CHECK_AGTALK_STATUS: 'CHECK_AGTALK_STATUS',
  AGTALK_PEERS: 'AGTALK_PEERS',
  DELIVER_TO_ACTIVE_TAB: 'DELIVER_TO_ACTIVE_TAB',
  ASSOCIATE_TAB_PEER: 'ASSOCIATE_TAB_PEER',
  GET_TAB_ASSOCIATION: 'GET_TAB_ASSOCIATION',
  SET_AUTO_REPLY_PEER: 'SET_AUTO_REPLY_PEER',
  GET_AUTO_REPLY_PEER: 'GET_AUTO_REPLY_PEER',
  PAUSE_AUTO_REPLY: 'PAUSE_AUTO_REPLY',
  PAUSE_ALL_AUTO_REPLY: 'PAUSE_ALL_AUTO_REPLY',
  GET_CONNECTED_PEERS: 'GET_CONNECTED_PEERS',
  OPEN_INBOX: 'OPEN_INBOX',
  AGTALK_DETAIL: 'AGTALK_DETAIL',
  AGTALK_ATTACHMENT: 'AGTALK_ATTACHMENT',
} as const;

export type MessageTypeValue = (typeof MessageType)[keyof typeof MessageType];
